version: '3'

networks:
  eoffice:

services:
  app:
    image: nginx:stable-alpine
    container_name: service-eoffice-nginx
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - eoffice
    extra_hosts:
      - "dockerhost:10.17.1.27"

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000"
    networks:
      - eoffice

  composer:
    image: composer:latest
    container_name: service-eoffice-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - eoffice

  npm:
    image: node:13.7
    container_name: service-eoffice-npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: service-eoffice-artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - eoffice
